/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
package inferencesvc

import (
	context "context"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestInferencePB(t *testing.T) {
	t.Parallel()

	req := &InferenceRequest{
		FeatureNames: []string{"test1", "test2"},
		PodRequestEntries: map[string]*ContainerRequestEntries{
			"pod1": {
				ContainerFeatureValues: map[string]*FeatureValues{
					"container1": {
						Values: []string{"1", "2"},
					},
				},
			},
		},
	}
	_ = req.String()
	req.ProtoMessage()
	req.XXX_Size()
	req.XXX_Merge(req)
	req.XXX_Unmarshal(nil)
	req.XXX_DiscardUnknown()
	req.GetPodRequestEntries()
	req.GetFeatureNames()
	bytes, err := req.Marshal()
	require.NoError(t, err)
	err = req.Unmarshal(bytes)
	require.NoError(t, err)
	req.Reset()

	resp := &InferenceResponse{
		PodResponseEntries: map[string]*ContainerResponseEntries{
			"pod1": {
				ContainerInferenceResults: map[string]*InferenceResult{
					"container1": {
						IsDefault:                false,
						ClassificationProb:       60,
						RegressionPredict:        60,
						ClassificationPercentile: 55,
						RegressionPercentile:     55,
					},
				},
			},
		},
	}
	_ = resp.String()
	resp.ProtoMessage()
	resp.XXX_Size()
	resp.XXX_Merge(resp)
	resp.XXX_Unmarshal(nil)
	resp.XXX_DiscardUnknown()
	resp.GetPodResponseEntries()
	bytes, err = resp.Marshal()
	require.NoError(t, err)
	err = resp.Unmarshal(bytes)
	require.NoError(t, err)
	resp.Reset()

	containerRequestEntries := &ContainerRequestEntries{
		ContainerFeatureValues: map[string]*FeatureValues{
			"container1": {
				Values: []string{"1", "2"},
			},
		},
	}
	_ = containerRequestEntries.String()
	containerRequestEntries.ProtoMessage()
	containerRequestEntries.XXX_Size()
	containerRequestEntries.XXX_Merge(containerRequestEntries)
	containerRequestEntries.XXX_Unmarshal(nil)
	containerRequestEntries.XXX_DiscardUnknown()
	containerRequestEntries.GetContainerFeatureValues()
	bytes, err = containerRequestEntries.Marshal()
	require.NoError(t, err)
	err = containerRequestEntries.Unmarshal(bytes)
	require.NoError(t, err)
	containerRequestEntries.Reset()

	featureValues := &FeatureValues{
		Values: []string{"1", "2"},
	}
	_ = featureValues.String()
	featureValues.ProtoMessage()
	featureValues.XXX_Size()
	featureValues.XXX_Merge(featureValues)
	featureValues.XXX_Unmarshal(nil)
	featureValues.XXX_DiscardUnknown()
	featureValues.GetValues()
	bytes, err = featureValues.Marshal()
	require.NoError(t, err)
	err = featureValues.Unmarshal(bytes)
	require.NoError(t, err)
	featureValues.Reset()

	containerResponseEntries := &ContainerResponseEntries{
		ContainerInferenceResults: map[string]*InferenceResult{
			"container1": {
				IsDefault:                false,
				ClassificationProb:       60,
				RegressionPredict:        60,
				ClassificationPercentile: 55,
				RegressionPercentile:     55,
			},
		},
	}
	_ = containerResponseEntries.String()
	containerResponseEntries.ProtoMessage()
	containerResponseEntries.XXX_Size()
	containerResponseEntries.XXX_Merge(containerResponseEntries)
	containerResponseEntries.XXX_Unmarshal(nil)
	containerResponseEntries.XXX_DiscardUnknown()
	containerResponseEntries.GetContainerInferenceResults()
	bytes, err = containerResponseEntries.Marshal()
	require.NoError(t, err)
	err = containerResponseEntries.Unmarshal(bytes)
	require.NoError(t, err)
	containerResponseEntries.Reset()

	inferenceResult := &InferenceResult{
		IsDefault:                false,
		ClassificationProb:       60,
		RegressionPredict:        60,
		ClassificationPercentile: 55,
		RegressionPercentile:     55,
	}
	_ = inferenceResult.String()
	inferenceResult.ProtoMessage()
	inferenceResult.XXX_Size()
	inferenceResult.XXX_Merge(inferenceResult)
	inferenceResult.XXX_Unmarshal(nil)
	inferenceResult.XXX_DiscardUnknown()
	inferenceResult.GetIsDefault()
	inferenceResult.GetClassificationProb()
	inferenceResult.GetRegressionPercentile()
	inferenceResult.GetRegressionPredict()
	inferenceResult.GetClassificationPercentile()
	bytes, err = inferenceResult.Marshal()
	require.NoError(t, err)
	err = inferenceResult.Unmarshal(bytes)
	require.NoError(t, err)
	inferenceResult.Reset()
}

func TestInference(t *testing.T) {
	t.Parallel()

	testServer := &UnimplementedInferenceServiceServer{}
	testServer.Inference(context.Background(), &InferenceRequest{})
}
