coverage:
  status:
    project:
      # global coverage
      default:
        target: auto
        threshold: 2%
        flags:
          - unittest
        paths:
          - "pkg"
        if_ci_failed: error
        if_no_uploads: error
        if_not_found: success
    patch:
      # diff coverage
      default:
        target: 50%
        flags:
          - unittest
        paths:
          - "pkg"
        if_ci_failed: error
        if_no_uploads: error
        if_not_found: success

ignore:
  - "**/*_generated.*"

github_checks:
  annotations: true
