# Copyright 2022 The Katalyst Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reclaimed-pod
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reclaimed-pod
  template:
    metadata:
      annotations:
        katalyst.kubewharf.io/qos_level: reclaimed_cores
      labels:
        app: reclaimed-pod
    spec:
      containers:
        - name: stress
          image: joedval/stress:latest
          command:
            - stress
            - -c
            - "1"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              resource.katalyst.kubewharf.io/reclaimed_millicpu: 4k
              resource.katalyst.kubewharf.io/reclaimed_memory: 16Gi
            limits:
              resource.katalyst.kubewharf.io/reclaimed_millicpu: 4k
              resource.katalyst.kubewharf.io/reclaimed_memory: 16Gi
      schedulerName: katalyst-scheduler