/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package machine

import (
	info "github.com/google/cadvisor/info/v1"
)

// KatalystMachineInfo is a combination of machine info generated by cadvisor,
// along with the extra info customized in katalyst environment
type KatalystMachineInfo struct {
	*info.MachineInfo

	// actually, CPUTopology can be generated by info.MachineInfo,
	// but we still keep it since it construct topology info in a
	// more convenient way
	*CPUTopology

	*MemoryTopology

	// ExtraCPUInfo is extra cpu info not in MachineInfo, such as
	// supported instructions
	*ExtraCPUInfo

	// ExtraNetworkInfo is extra network info not in MachineInfo,
	// such as numa node of each interface
	*ExtraNetworkInfo
}
